from tkinter import *
from datetime import date
root = Tk()
root.title("Age Calculator App")
root.geometry("400x400")
frame=Frame(master=root,height=220,width=360,bg="#d0efff")
lbl1=Label(frame,text="Name",bg="lightblue",fg="white",width=12)
lbl2=Label(frame,text="Day",bg="lightblue",fg="white",width=12)
lbl3=Label(frame,text="Month",bg="lightblue",fg="white",width=12)
lbl4=Label(frame,text="Year",bg="lightblue",fg="white",width=12)
name_enter=Entry(frame)
day_enter=Entry(frame)
month_enter=Entry(frame)
year_enter=Entry(frame)
def calculate_age():
    name=str(name_enter.get())
    day=int(day_enter.get())
    month=str(month_enter.get())
    year=int(year_enter.get())
    today=date.today()
    age=today.year-year
    if (today.month, today.day) < (int(month), day):
        age -= 1
    textbox.insert(END,"Hello "+name+"!\n")
    textbox.insert(END,"Your Age is: "+str(age)+" years")
btn=Button(frame,text="Calculate Age",command=calculate_age,bg='red',fg='white')
textbox=Text(bg="#BEBEBE",fg="black",height=4,width=40)
frame.place(x=20,y=0)
lbl1.place(x=20,y=20)
name_enter.place(x=150,y=20)
lbl2.place(x=20,y=60)
day_enter.place(x=150,y=60)
lbl3.place(x=20,y=100)
month_enter.place(x=150,y=100)
lbl4.place(x=20,y=140)
year_enter.place(x=150,y=140)
btn.place(x=140,y=210)
textbox.place(x=20,y=260)
root.mainloop()
